#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use Fulll\Infra\Database\DatabaseManager;
use Fulll\Infra\Repository\FleetSqliteRepository;
use Fulll\Infra\Repository\FleetTemporaryRepository;
use Fulll\Infra\CLI\CommandHandler;
use Fulll\Infra\CLI\FleetArgumentValidator;
use Fulll\Infra\Repository\LocationSqliteRepository;
use Fulll\Infra\Repository\VehicleSqliteRepository;

//$repository = new FleetTemporaryRepository();

$pdo = new PDO('sqlite:' . __DIR__ . '/database.sqlite');
DatabaseManager::initialize($pdo);

$fleetRepository = new FleetSqliteRepository($pdo);
$vehicleRepository = new VehicleSqliteRepository($pdo);
$locationRepository = new LocationSqliteRepository($pdo);

$args = $argv;
array_shift($args);

try {
    $command = FleetArgumentValidator::getCommand($args);
    FleetArgumentValidator::checkIsSupported($command);
    CommandHandler::handle($command, $args, $fleetRepository, $vehicleRepository, $locationRepository);
} catch (Exception $e) {
    echo $e->getMessage() . PHP_EOL;
    exit(1);
}
