name: Run Behat tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  behat-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none

      - name: Install Composer dependencies
        run: composer install
        working-directory: Backend

      - name: Run Behat tests
        run: vendor/bin/behat --profile=ci
        working-directory: Backend

      - name: Upload JUnit report
        uses: actions/upload-artifact@v4
        with:
          name: behat-junit-report
          path: Backend/build/logs/behat-junit.xml
